services:
  postgres:
    image: postgres:16-alpine
    container_name: evi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eviadmin
      POSTGRES_PASSWORD: evi123
      POSTGRES_DB: evi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: